---
title: "Graphics Practice File"
author: "Ginny Eckert"
date: "11/7/2019"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r, message=FALSE, warning=FALSE}
  library(leaflet)
  library(dplyr)
  library(tidyr)
  library(ggplot2)
  library(DT)
  library(scales) # install.packages("scales")
```

# Prepare Data

```{r}
data_url <- "https://knb.ecoinformatics.org/knb/d1/mn/v2/object/urn%3Auuid%3Af119a05b-bbe7-4aea-93c6-85434dcb1c5e"

esc <- tryCatch(
    read.csv("data/escapement.csv", stringsAsFactors = FALSE),
    error=function(cond) {
        message(paste("Escapement file does not seem to exist, so get it from the KNB."))
        esc <- read.csv(url(data_url, method = "libcurl"), stringsAsFactors = FALSE)
        write.csv(esc, "Data/escapement.csv", row.names=F)
        return(esc)
    }
)

#head(esc)
```

Calculate annual escapement by Species, Region, Year for Sockeye, Chinook, Coho, Pink, Chum

```{r}
esc_date_split <- esc %>% 
  #separate(sampleDate, into = c("Year", "Month", "Day"), sep = "-")
  mutate(Year = lubridate::year(as.Date(sampleDate)))
#esc_date_split
```

```{r}
esc_sum <- esc_date_split %>% 
  filter(Species %in% c("Sockeye", "Chinook", "Coho", "Pink", "Chum")) %>% 
  group_by(Species, SASAP.Region, Year) %>% 
  summarize(AnnualCount = sum(DailyCount)) 
#esc_sum
```

# Create static plots

```{r}
ggplot(esc_sum, mapping=aes(x=Species, y=AnnualCount)) +
  geom_col(fill="blue")
```

```{r}
ggplot(esc_sum, mapping=aes(x=Species, y=AnnualCount, fill=SASAP.Region)) +
  geom_col()
```

```{r}
esc_sumKodiak <- esc_sum %>% 
  filter(SASAP.Region == "Kodiak")

mytheme <- theme_bw() +
  theme(legend.position="bottom")
    
  ggplot(esc_sumKodiak, mapping=aes(x=Year, y=AnnualCount, color=Species)) +
  geom_line() +
  geom_point() +
    scale_y_continuous(labels=comma) +
    scale_color_brewer(palette=1) +
      # check out R color pdf and http://colorbrewer2.org
    ylab("Escapement (num.fish)") +
    ggtitle("Kodiak Salmon Escapement") +
   mytheme
```

```{r}
p1 <- ggplot(esc_sum, mapping=aes(x=Year, y=AnnualCount, color=Species)) +
  geom_line() +
  geom_point() +
  facet_wrap(~SASAP.Region) +
  scale_y_continuous(labels=comma) +
  ylab ("Escapement(num.fish)") +
  mytheme

p1

ggsave("figure.png", p1, height = 7, width = 7, units = "in", dpi=300)
```

# Create an interactive table


```{r}
locations <- esc %>% 
  distinct(Location, Latitude, Longitude) %>% 
  drop_na()

```

```{r}
datatable((locations))
```

# Create an interactive map

```{r}
leaflet(locations) %>% 
  addTiles() %>% 
  addMarkers(lng = ~Longitude, lat= ~Latitude, popup = ~Location)
```

Use a fancier map
```{r}
leaflet(locations) %>% 
  addWMSTiles("https://www.gebco.net/data_and_products/gebco_web_services/web_map_service/mapserv?",
              layers = 'GEBCO_LATEST',
              attribution = "Imagery reproduced from the GEBCO_2014 Grid, version 20150318, www.gebco.net") %>%
  addCircleMarkers(lng = ~Longitude,
                   lat = ~Latitude,
                   popup = ~ Location,
                   radius = 5,
                   # set fill properties
                   fillColor = "salmon",
                   fillOpacity = 1,
                   # set stroke properties
                   stroke = T,
                   weight = 0.5,
                   color = "white",
                   opacity = 1)
```

